In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.ensemble import VotingClassifier
from keras.layers import Activation, Dense, Dropout, BatchNormalization
from keras.models import Sequential
from keras.utils.np_utils import to_categorical
from keras.datasets import mnist
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import train_test_split
from keras import optimizers

C:\Users\gunja\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Using TensorFlow backend.


In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [4]:
x_train = x_train.reshape((x_train.shape[0], -1))

In [5]:
print(x_train.shape)

(60000, 784)


In [6]:
x_test = x_test.reshape((x_test.shape[0], -1))

In [7]:
# y_train = to_categorical(y_train, num_classes=10, dtype = int)

In [7]:
print(y_train.shape)

(60000,)


In [9]:
# y_test = to_categorical(y_test, num_classes = 10, dtype = int)

In [8]:
# print(y_test[:5, : ])

IndexError: too many indices for array

In [11]:
# print(y_train[:5, :])

[[0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [17]:
def mlp_model():
    model = Sequential()
    
    model.add(Dense(50, input_shape=(784, ), kernel_initializer = 'he_normal'))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(Dense(50, kernel_initializer = 'he_normal'))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(Dense(50, kernel_initializer = 'he_normal'))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(Dense(50, kernel_initializer = 'he_normal'))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(Dense(10, kernel_initializer = 'he_normal'))
#     model.add(BatchNormalization())
    model.add(Activation('softmax'))
#     model.add(Dropout(0.2))
    
    adam = optimizers.Adam(lr = 0.001)
    model.compile(optimizer = adam, loss = 'categorical_crossentropy', metrics = ['acc'])
    return model

In [18]:
model1 = KerasClassifier(build_fn = mlp_model, epochs = 100, validation_split = 0.3)
model2 = KerasClassifier(build_fn = mlp_model, epochs = 100, validation_split = 0.3)
model3 = KerasClassifier(build_fn = mlp_model, epochs = 100, validation_split = 0.3)
model4 = KerasClassifier(build_fn = mlp_model, epochs = 100, validation_split = 0.3)
model5 = KerasClassifier(build_fn = mlp_model, epochs = 100, validation_split = 0.3)

In [21]:
ensemble_clf = VotingClassifier(estimators = [('model1', model1), ('model2', model2)], voting = 'soft')

In [22]:
ensemble_clf.fit(x_train, y_train)

Train on 42000 samples, validate on 18000 samples
Epoch 1/100
42000/42000 [==============================] - 21s 507us/step - loss: 0.8740 - acc: 0.7241 - val_loss: 0.2714 - val_acc: 0.9229
Epoch 2/100
42000/42000 [==============================] - 19s 458us/step - loss: 0.4993 - acc: 0.8550 - val_loss: 0.2099 - val_acc: 0.9395
Epoch 3/100
42000/42000 [==============================] - 20s 467us/step - loss: 0.4176 - acc: 0.8784 - val_loss: 0.1827 - val_acc: 0.9474
Epoch 4/100
42000/42000 [==============================] - 22s 524us/step - loss: 0.3732 - acc: 0.8940 - val_loss: 0.1743 - val_acc: 0.9494
Epoch 5/100
42000/42000 [==============================] - 23s 557us/step - loss: 0.3394 - acc: 0.9033 - val_loss: 0.1612 - val_acc: 0.9527
Epoch 6/100
42000/42000 [==============================] - 22s 525us/step - loss: 0.3081 - acc: 0.9112 - val_loss: 0.1490 - val_acc: 0.9552
Epoch 7/100
42000/42000 [==============================] - 22s 518us/step - loss: 0.3003 - acc: 0.9145 - val_l

42000/42000 [==============================] - 21s 505us/step - loss: 0.1619 - acc: 0.9518 - val_loss: 0.1045 - val_acc: 0.9706
Epoch 59/100
42000/42000 [==============================] - 21s 505us/step - loss: 0.1584 - acc: 0.9538 - val_loss: 0.1054 - val_acc: 0.9696
Epoch 60/100
42000/42000 [==============================] - 20s 473us/step - loss: 0.1555 - acc: 0.9540 - val_loss: 0.1039 - val_acc: 0.9708
Epoch 61/100
42000/42000 [==============================] - 20s 474us/step - loss: 0.1548 - acc: 0.9534 - val_loss: 0.1056 - val_acc: 0.9696
Epoch 62/100
42000/42000 [==============================] - 20s 469us/step - loss: 0.1568 - acc: 0.9541 - val_loss: 0.1085 - val_acc: 0.9694
Epoch 63/100
42000/42000 [==============================] - 20s 470us/step - loss: 0.1552 - acc: 0.9545 - val_loss: 0.1064 - val_acc: 0.9691
Epoch 64/100
42000/42000 [==============================] - 20s 470us/step - loss: 0.1530 - acc: 0.9547 - val_loss: 0.1049 - val_acc: 0.9697
Epoch 65/100
42000/42000 [

42000/42000 [==============================] - 23s 538us/step - loss: 0.2265 - acc: 0.9345 - val_loss: 0.1113 - val_acc: 0.9664
Epoch 16/100
42000/42000 [==============================] - 24s 563us/step - loss: 0.2204 - acc: 0.9366 - val_loss: 0.1126 - val_acc: 0.9672
Epoch 17/100
42000/42000 [==============================] - 22s 529us/step - loss: 0.2143 - acc: 0.9383 - val_loss: 0.1052 - val_acc: 0.9689
Epoch 18/100
42000/42000 [==============================] - 22s 533us/step - loss: 0.2118 - acc: 0.9389 - val_loss: 0.1080 - val_acc: 0.9676
Epoch 19/100
42000/42000 [==============================] - 24s 572us/step - loss: 0.2096 - acc: 0.9406 - val_loss: 0.1064 - val_acc: 0.9690: 0.94
Epoch 20/100
42000/42000 [==============================] - 23s 540us/step - loss: 0.2047 - acc: 0.9401 - val_loss: 0.1044 - val_acc: 0.9683
Epoch 21/100
42000/42000 [==============================] - 23s 547us/step - loss: 0.2078 - acc: 0.9399 - val_loss: 0.1043 - val_acc: 0.96879s - loss: 0 - ETA: 9

Epoch 73/100
42000/42000 [==============================] - 19s 454us/step - loss: 0.1510 - acc: 0.9565 - val_loss: 0.0973 - val_acc: 0.9705
Epoch 74/100
42000/42000 [==============================] - 19s 453us/step - loss: 0.1489 - acc: 0.9562 - val_loss: 0.0958 - val_acc: 0.9717
Epoch 75/100
42000/42000 [==============================] - 19s 458us/step - loss: 0.1424 - acc: 0.9567 - val_loss: 0.0935 - val_acc: 0.9721
Epoch 76/100
42000/42000 [==============================] - 20s 473us/step - loss: 0.1528 - acc: 0.9547 - val_loss: 0.0942 - val_acc: 0.9726
Epoch 77/100
42000/42000 [==============================] - 19s 453us/step - loss: 0.1468 - acc: 0.9578 - val_loss: 0.0934 - val_acc: 0.9725
Epoch 78/100
42000/42000 [==============================] - 19s 451us/step - loss: 0.1474 - acc: 0.9570 - val_loss: 0.0930 - val_acc: 0.9722
Epoch 79/100
42000/42000 [==============================] - 19s 452us/step - loss: 0.1474 - acc: 0.9555 - val_loss: 0.0958 - val_acc: 0.9711
Epoch 80/100


VotingClassifier(estimators=[('model1', <keras.wrappers.scikit_learn.KerasClassifier object at 0x0000024FAD171080>), ('model2', <keras.wrappers.scikit_learn.KerasClassifier object at 0x0000024FAD171D30>)],
         flatten_transform=None, n_jobs=1, voting='soft', weights=None)

In [23]:
y_pred = ensemble_clf.predict(x_test)

C:\Users\gunja\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [24]:
print('Acc:', accuracy_score(y_test, y_pred))

Acc: 0.9769
